package tools

import (
	"encoding/json"
	"fmt"
	"reflect"
	"regexp"
	"runtime"
	"strconv"
	"strings"
)

// ToolParameter 工具参数定义
type ToolParameter struct {
	Name        string      `json:"name"`
	Type        string      `json:"type"`
	Description string      `json:"description"`
	Required    bool        `json:"required"`
	Default     interface{} `json:"default,omitempty"`
}

// Tool 工具接口
type Tool interface {
	// Name 返回工具名称
	Name() string
	// Description 返回工具描述
	Description() string
	// Run 执行工具
	Run(parameters map[string]interface{}) (string, error)
	// GetParameters 获取工具参数定义
	GetParameters() []ToolParameter
	// ValidateParameters 验证参数
	ValidateParameters(parameters map[string]interface{}) bool
	// ToDict 转换为字典格式
	ToDict() map[string]interface{}
	// ToOpenAISchema 转换为 OpenAI function calling schema 格式
	ToOpenAISchema() map[string]interface{}
	// GetExpandedTools 获取展开后的子工具列表
	GetExpandedTools() []Tool
}

// toolActionData 工具动作数据（用于替代 Python 的 @tool_action 装饰器属性）
type toolActionData struct {
	isToolAction  bool
	toolName      string
	toolDesc      string
	method        reflect.Method
	parameters    []ToolParameter
}

// BaseTool 工具基类，提供默认实现
type BaseTool struct {
	name        string
	description string
	expandable  bool
	// _tool_actions 存储标记为工具动作的方法（对应 Python 的 @tool_action 装饰器标记的方法）
	_toolActions []toolActionData
}

// NewBaseTool 创建工具基类
func NewBaseTool(name, description string, expandable bool) *BaseTool {
	return &BaseTool{
		name:         name,
		description:  description,
		expandable:   expandable,
		_toolActions: nil,
	}
}

// Name 返回工具名称
func (t *BaseTool) Name() string {
	return t.name
}

// Description 返回工具描述
func (t *BaseTool) Description() string {
	return t.description
}

// Run 执行工具，子类必须实现
func (t *BaseTool) Run(parameters map[string]interface{}) (string, error) {
	return "", fmt.Errorf("Run method must be implemented by concrete tool")
}

// GetParameters 获取工具参数定义，子类可以重写
func (t *BaseTool) GetParameters() []ToolParameter {
	return nil
}

// GetExpandedTools 获取展开后的子工具列表
// 默认实现：自动从标记了 @tool_action 的方法生成子工具
// 子类可以重写此方法提供自定义的展开逻辑
func (t *BaseTool) GetExpandedTools() []Tool {
	if !t.expandable {
		return nil
	}

	// 自动从装饰器标记的方法生成工具
	tools := make([]Tool, 0)
	for _, action := range t._toolActions {
		if action.isToolAction {
			tool := NewAutoGeneratedTool(t, action.method, action.toolName, action.toolDesc)
			tools = append(tools, tool)
		}
	}

	if len(tools) == 0 {
		return nil
	}
	return tools
}

// ValidateParameters 验证参数
func (t *BaseTool) ValidateParameters(parameters map[string]interface{}) bool {
	requiredParams := make([]string, 0)
	for _, p := range t.GetParameters() {
		if p.Required {
			requiredParams = append(requiredParams, p.Name)
		}
	}
	for _, param := range requiredParams {
		if _, exists := parameters[param]; !exists {
			return false
		}
	}
	return true
}

// ToDict 转换为字典格式
func (t *BaseTool) ToDict() map[string]interface{} {
	params := make([]map[string]interface{}, 0)
	for _, param := range t.GetParameters() {
		params = append(params, map[string]interface{}{
			"name":        param.Name,
			"type":        param.Type,
			"description": param.Description,
			"required":    param.Required,
			"default":     param.Default,
		})
	}
	return map[string]interface{}{
		"name":        t.name,
		"description": t.description,
		"parameters":  params,
	}
}

// ToOpenAISchema 转换为 OpenAI function calling schema 格式
func (t *BaseTool) ToOpenAISchema() map[string]interface{} {
	parameters := t.GetParameters()

	// 构建 properties
	properties := make(map[string]interface{})
	required := make([]string, 0)

	for _, param := range parameters {
		// 基础属性定义
		prop := map[string]interface{}{
			"type":        param.Type,
			"description": param.Description,
		}

		// 如果有默认值，添加到描述中（OpenAI schema 不支持 default 字段）
		if param.Default != nil {
			prop["description"] = fmt.Sprintf("%s (默认: %v)", param.Description, param.Default)
		}

		// 如果是数组类型，添加 items 定义
		if param.Type == "array" {
			prop["items"] = map[string]string{"type": "string"} // 默认字符串数组
		}

		properties[param.Name] = prop

		// 收集必需参数
		if param.Required {
			required = append(required, param.Name)
		}
	}

	return map[string]interface{}{
		"type": "function",
		"function": map[string]interface{}{
			"name":        t.name,
			"description": t.description,
			"parameters": map[string]interface{}{
				"type":       "object",
				"properties": properties,
				"required":   required,
			},
		},
	}
}

// String 返回字符串表示（对应 Python 的 __str__）
func (t *BaseTool) String() string {
	return fmt.Sprintf("Tool(name=%s)", t.name)
}

// RegisterToolAction 注册工具动作（用于替代 Python 的 @tool_action 装饰器）
// 在 Go 中，需要在构造函数中手动调用此方法来注册工具动作
func (t *BaseTool) RegisterToolAction(method reflect.Method, name, description string) {
	t._toolActions = append(t._toolActions, toolActionData{
		isToolAction: true,
		toolName:     name,
		toolDesc:     description,
		method:       method,
	})
}

// AutoGeneratedTool 自动生成的工具 - 从方法签名和 docstring 自动提取参数
type AutoGeneratedTool struct {
	parent     Tool
	method     reflect.Method
	name       string
	description string
	_parameters []ToolParameter
}

// NewAutoGeneratedTool 创建自动生成的工具
// parent: 父工具实例
// method: 被装饰的方法
// name: 工具名称（如果为空，从方法名生成）
// description: 工具描述（如果为空，从 docstring 提取）
func NewAutoGeneratedTool(parent Tool, method reflect.Method, name, description string) *AutoGeneratedTool {
	t := &AutoGeneratedTool{
		parent: parent,
		method: method,
	}

	// 生成工具名称
	if name == "" {
		// 从方法名生成：_add_memory -> parent_name_add_memory
		methodName := strings.TrimLeft(method.Name, "_")
		name = fmt.Sprintf("%s_%s", parent.Name(), methodName)
	}
	t.name = name

	// 提取描述
	if description == "" {
		description = t._extractDescriptionFromDocstring()
	}
	t.description = description

	// 自动解析参数
	t._parameters = t._parseParameters()

	return t
}

// _extractDescriptionFromDocstring 从 docstring 提取描述
func (t *AutoGeneratedTool) _extractDescriptionFromDocstring() string {
	doc := runtime.FuncForPC(t.method.Func.Pointer()).Name()
	if doc == "" {
		return fmt.Sprintf("执行 %s", t.method.Name)
	}

	// 提取第一行作为描述
	lines := strings.Split(doc, "\n")
	for _, line := range lines {
		line = strings.TrimSpace(line)
		if line != "" && !strings.HasPrefix(line, "Args:") && !strings.HasPrefix(line, "Returns:") {
			return line
		}
	}

	return fmt.Sprintf("执行 %s", t.method.Name)
}

// _parseParameters 从方法签名和 docstring 自动提取参数
func (t *AutoGeneratedTool) _parseParameters() []ToolParameter {
	// 从 docstring 解析参数描述
	docstring := "" // Go 方法没有内置 docstring，需要其他方式获取
	paramDescriptions := t._parseParamDescriptions(docstring)

	parameters := make([]ToolParameter, 0)
	fnType := t.method.Type

	// 跳过接收器参数（第0个）
	for i := 1; i < fnType.NumIn(); i++ {
		paramType := fnType.In(i)
		paramName := fmt.Sprintf("param%d", i)

		// 获取类型
		paramTypeStr := t._pythonTypeToToolType(paramType)

		// 判断是否必需（Go 没有默认值，都视为必需）
		required := true
		var defaultValue interface{} = nil

		// 获取描述
		description := paramDescriptions[paramName]
		if description == "" {
			description = fmt.Sprintf("参数 %s", paramName)
		}

		parameters = append(parameters, ToolParameter{
			Name:        paramName,
			Type:        paramTypeStr,
			Description: description,
			Required:    required,
			Default:     defaultValue,
		})
	}

	return parameters
}

// _parseParamDescriptions 从 docstring 解析参数描述
// 支持格式:
//
//	Args:
//	    param_name: 参数描述
//	    another_param: 另一个参数描述
func (t *AutoGeneratedTool) _parseParamDescriptions(docstring string) map[string]string {
	descriptions := make(map[string]string)

	// 查找 Args: 部分
	argsPattern := regexp.MustCompile(`(?s)Args:\s*\n(.*?)(?:\n\s*\n|Returns:|$)`)
	argsMatch := argsPattern.FindStringSubmatch(docstring)
	if argsMatch == nil {
		return descriptions
	}

	argsSection := argsMatch[1]

	// 解析每个参数
	// 匹配格式: param_name: 描述 或 param_name (type): 描述
	paramPattern := regexp.MustCompile(`(?m)^\s*(\w+)(?:\s*\([^)]+\))?\s*:\s*(.+?)(?=^\s*\w+\s*(?:\([^)]+\))?\s*:|$)`)
	matches := paramPattern.FindAllStringSubmatch(argsSection, -1)

	for _, match := range matches {
		if len(match) >= 3 {
			paramName := strings.TrimSpace(match[1])
			paramDesc := strings.TrimSpace(match[2])
			// 清理描述中的多余空白
			paramDesc = regexp.MustCompile(`\s+`).ReplaceAllString(paramDesc, " ")
			descriptions[paramName] = paramDesc
		}
	}

	return descriptions
}

// _pythonTypeToToolType 将类型转换为工具类型字符串
func (t *AutoGeneratedTool) _pythonTypeToToolType(goType reflect.Type) string {
	// 处理基本类型
	typeMap := map[reflect.Kind]string{
		reflect.String:  "string",
		reflect.Int:     "integer",
		reflect.Int8:    "integer",
		reflect.Int16:   "integer",
		reflect.Int32:   "integer",
		reflect.Int64:   "integer",
		reflect.Uint:    "integer",
		reflect.Uint8:   "integer",
		reflect.Uint16:  "integer",
		reflect.Uint32:  "integer",
		reflect.Uint64:  "integer",
		reflect.Float32: "number",
		reflect.Float64: "number",
		reflect.Bool:    "boolean",
		reflect.Slice:   "array",
		reflect.Array:   "array",
		reflect.Map:     "object",
	}

	if result, ok := typeMap[goType.Kind()]; ok {
		return result
	}
	return "string"
}

// GetParameters 获取参数列表
func (t *AutoGeneratedTool) GetParameters() []ToolParameter {
	return t._parameters
}

// Run 执行方法
func (t *AutoGeneratedTool) Run(parameters map[string]interface{}) (string, error) {
	// 通过反射调用方法
	args := make([]reflect.Value, 0)
	args = append(args, reflect.ValueOf(t.parent))

	// 按参数顺序构建参数列表
	for _, param := range t._parameters {
		if val, ok := parameters[param.Name]; ok {
			args = append(args, reflect.ValueOf(val))
		}
	}

	results := t.method.Func.Call(args)
	if len(results) > 0 {
		if str, ok := results[0].Interface().(string); ok {
			var err error
			if len(results) > 1 {
				err, _ = results[1].Interface().(error)
			}
			return str, err
		}
	}
	return "", nil
}

// Name 返回工具名称
func (t *AutoGeneratedTool) Name() string {
	return t.name
}

// Description 返回工具描述
func (t *AutoGeneratedTool) Description() string {
	return t.description
}

// ValidateParameters 验证参数
func (t *AutoGeneratedTool) ValidateParameters(parameters map[string]interface{}) bool {
	for _, param := range t._parameters {
		if param.Required {
			if _, exists := parameters[param.Name]; !exists {
				return false
			}
		}
	}
	return true
}

// ToDict 转换为字典格式
func (t *AutoGeneratedTool) ToDict() map[string]interface{} {
	params := make([]map[string]interface{}, 0)
	for _, param := range t._parameters {
		params = append(params, map[string]interface{}{
			"name":        param.Name,
			"type":        param.Type,
			"description": param.Description,
			"required":    param.Required,
			"default":     param.Default,
		})
	}
	return map[string]interface{}{
		"name":        t.name,
		"description": t.description,
		"parameters":  params,
	}
}

// ToOpenAISchema 转换为 OpenAI function calling schema 格式
func (t *AutoGeneratedTool) ToOpenAISchema() map[string]interface{} {
	properties := make(map[string]interface{})
	required := make([]string, 0)

	for _, param := range t._parameters {
		prop := map[string]interface{}{
			"type":        param.Type,
			"description": param.Description,
		}

		if param.Default != nil {
			prop["description"] = fmt.Sprintf("%s (默认: %v)", param.Description, param.Default)
		}

		if param.Type == "array" {
			prop["items"] = map[string]string{"type": "string"}
		}

		properties[param.Name] = prop

		if param.Required {
			required = append(required, param.Name)
		}
	}

	return map[string]interface{}{
		"type": "function",
		"function": map[string]interface{}{
			"name":        t.name,
			"description": t.description,
			"parameters": map[string]interface{}{
				"type":       "object",
				"properties": properties,
				"required":   required,
			},
		},
	}
}

// GetExpandedTools 返回 nil（自动生成的工具不支持展开）
func (t *AutoGeneratedTool) GetExpandedTools() []Tool {
	return nil
}

// String 返回字符串表示（对应 Python 的 __str__）
func (t *AutoGeneratedTool) String() string {
	return fmt.Sprintf("Tool(name=%s)", t.name)
}

// ==================== 辅助函数（Go 特有，Python 不需要）====================

// validateType 检查值是否匹配预期类型
func validateType(value interface{}, expectedType string) bool {
	if value == nil {
		return true
	}

	switch expectedType {
	case "string":
		_, ok := value.(string)
		return ok
	case "integer":
		switch value.(type) {
		case int, int8, int16, int32, int64, uint, uint8, uint16, uint32, uint64:
			return true
		case float64:
			f := value.(float64)
			return f == float64(int(f))
		case string:
			_, err := strconv.ParseInt(value.(string), 10, 64)
			return err == nil
		}
		return false
	case "number":
		switch value.(type) {
		case int, int8, int16, int32, int64, uint, uint8, uint16, uint32, uint64, float32, float64:
			return true
		case string:
			_, err := strconv.ParseFloat(value.(string), 64)
			return err == nil
		}
		return false
	case "boolean":
		switch v := value.(type) {
		case bool:
			return true
		case string:
			lowered := strings.ToLower(v)
			return lowered == "true" || lowered == "false"
		}
		return false
	case "array":
		rv := reflect.ValueOf(value)
		return rv.Kind() == reflect.Slice || rv.Kind() == reflect.Array
	case "object":
		_, ok := value.(map[string]interface{})
		return ok
	default:
		return true
	}
}

// ConvertParameters 将参数从各种类型转换为 map[string]interface{}
func ConvertParameters(params interface{}) (map[string]interface{}, error) {
	switch v := params.(type) {
	case map[string]interface{}:
		return v, nil
	case string:
		var result map[string]interface{}
		if err := json.Unmarshal([]byte(v), &result); err != nil {
			return nil, fmt.Errorf("解析 JSON 参数失败: %w", err)
		}
		return result, nil
	case nil:
		return make(map[string]interface{}), nil
	default:
		rv := reflect.ValueOf(params)
		if rv.Kind() == reflect.Map {
			result := make(map[string]interface{})
			for _, key := range rv.MapKeys() {
				val := rv.MapIndex(key)
				result[key.String()] = val.Interface()
			}
			return result, nil
		}
		return nil, fmt.Errorf("不支持的参数类型: %T", params)
	}
}
