package tools

import (
	"fmt"
	"sort"
	"time"
)

// ToolAction is a lightweight replacement for Python decorator metadata.
type ToolAction struct {
	Name        string
	Description string
}

func NewToolAction(name, description string) ToolAction {
	return ToolAction{Name: name, Description: description}
}

type ToolParameter struct {
	Name        string `json:"name"`
	Type        string `json:"type"`
	Description string `json:"description"`
	Required    bool   `json:"required"`
	Default     any    `json:"default,omitempty"`
}

// Tool is the base interface that all tools should satisfy.
type Tool interface {
	GetName() string
	GetDescription() string
	GetParameters() []ToolParameter
	Run(parameters map[string]any) ToolResponse
	RunWithTiming(parameters map[string]any) ToolResponse
}

// BaseTool provides reusable defaults.
type BaseTool struct {
	Name        string
	Description string
	Expandable  bool
	Parameters  map[string]ToolParameter
}

func NewBaseTool(name, description string, expandable bool) BaseTool {
	return BaseTool{
		Name:        name,
		Description: description,
		Expandable:  expandable,
		Parameters:  map[string]ToolParameter{},
	}
}

func (t *BaseTool) GetName() string { return t.Name }

func (t *BaseTool) GetDescription() string { return t.Description }

func (t *BaseTool) Run(parameters map[string]any) ToolResponse {
	return Error("tool run() not implemented", ToolErrorCodeInternalError, map[string]any{"tool": t.Name})
}

func (t *BaseTool) GetParameters() []ToolParameter {
	out := make([]ToolParameter, 0, len(t.Parameters))
	for _, p := range t.Parameters {
		out = append(out, p)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Name < out[j].Name })
	return out
}

func (t *BaseTool) RunWithTiming(parameters map[string]any) (resp ToolResponse) {
	start := time.Now()
	defer func() {
		elapsedMS := time.Since(start).Milliseconds()
		if recovered := recover(); recovered != nil {
			resp = Error(
				fmt.Sprintf("工具执行时发生未处理的异常: %v", recovered),
				ToolErrorCodeInternalError,
				nil,
			)
		}
		if resp.Stats == nil {
			resp.Stats = map[string]any{}
		}
		resp.Stats["time_ms"] = elapsedMS
		if resp.Context == nil {
			resp.Context = map[string]any{}
		}
		resp.Context["params_input"] = parameters
		resp.Context["tool_name"] = t.Name
	}()

	resp = t.Run(parameters)
	return resp
}

func (t *BaseTool) ARun(parameters map[string]any) ToolResponse {
	return t.Run(parameters)
}

func (t *BaseTool) ARunWithTiming(parameters map[string]any) ToolResponse {
	return t.RunWithTiming(parameters)
}

func (t *BaseTool) GetExpandedTools() []Tool {
	return nil
}

func (t *BaseTool) ValidateParameters(parameters map[string]any) bool {
	for _, p := range t.Parameters {
		if p.Required {
			if _, ok := parameters[p.Name]; !ok {
				return false
			}
		}
	}
	return true
}

func (t *BaseTool) ToMap() map[string]any {
	params := make([]map[string]any, 0)
	for _, p := range t.GetParameters() {
		params = append(params, map[string]any{
			"name":        p.Name,
			"type":        p.Type,
			"description": p.Description,
			"required":    p.Required,
			"default":     p.Default,
		})
	}
	return map[string]any{
		"name":        t.Name,
		"description": t.Description,
		"expandable":  t.Expandable,
		"parameters":  params,
	}
}

// ToDict keeps naming parity with Python Tool.to_dict().
func (t *BaseTool) ToDict() map[string]any {
	return t.ToMap()
}

func (t *BaseTool) ToOpenAISchema() map[string]any {
	properties := map[string]any{}
	required := make([]string, 0)
	for _, p := range t.GetParameters() {
		description := p.Description
		if p.Default != nil {
			description = fmt.Sprintf("%s (默认: %v)", p.Description, p.Default)
		}
		prop := map[string]any{
			"type":        p.Type,
			"description": description,
		}
		if p.Type == "array" {
			prop["items"] = map[string]any{"type": "string"}
		}
		properties[p.Name] = prop
		if p.Required {
			required = append(required, p.Name)
		}
	}
	schema := map[string]any{
		"type": "function",
		"function": map[string]any{
			"name":        t.Name,
			"description": t.Description,
			"parameters": map[string]any{
				"type":       "object",
				"properties": properties,
				"required":   required,
			},
		},
	}
	return schema
}

func (t *BaseTool) String() string {
	return fmt.Sprintf("Tool(name=%s)", t.Name)
}

// AutoGeneratedTool represents one generated action of an expandable tool.
type AutoGeneratedTool struct {
	BaseTool
	Parent Tool
	Method any
}

func NewAutoGeneratedTool(parent Tool, method any, name, description string) *AutoGeneratedTool {
	if name == "" {
		name = parent.GetName() + "Action"
	}
	if description == "" {
		description = "auto generated tool action"
	}
	t := &AutoGeneratedTool{
		BaseTool: NewBaseTool(name, description, false),
		Parent:   parent,
		Method:   method,
	}
	return t
}

func (t *AutoGeneratedTool) GetParameters() []ToolParameter {
	if len(t.BaseTool.Parameters) > 0 {
		return t.BaseTool.GetParameters()
	}
	if t.Parent != nil {
		return t.Parent.GetParameters()
	}
	return []ToolParameter{
		{
			Name:        "input",
			Type:        "object",
			Description: "工具参数字典",
			Required:    false,
		},
	}
}

func (t *AutoGeneratedTool) Run(parameters map[string]any) (resp ToolResponse) {
	if t.Method == nil {
		return Error("auto-generated tool action missing method", ToolErrorCodeInternalError, nil)
	}
	defer func() {
		if recovered := recover(); recovered != nil {
			resp = Error(fmt.Sprintf("方法执行失败: %v", recovered), ToolErrorCodeExecutionError, nil)
		}
	}()

	switch fn := t.Method.(type) {
	case func(map[string]any) ToolResponse:
		resp = fn(parameters)
		return resp
	case func(map[string]any) any:
		result := fn(parameters)
		if toolResp, ok := result.(ToolResponse); ok {
			resp = toolResp
			return resp
		}
		return Success(fmt.Sprintf("%v", result), map[string]any{"output": result}, nil, nil)
	case func(map[string]any) string:
		result := fn(parameters)
		return Success(result, map[string]any{"output": result}, nil, nil)
	default:
		return Error("auto-generated tool action method signature is unsupported", ToolErrorCodeExecutionError, nil)
	}
}
