package tools

import "testing"

func TestBaseToolToMapMatchesPythonShape(t *testing.T) {
	base := NewBaseTool("x", "desc", true)
	m := base.ToMap()
	if _, ok := m["expandable"]; ok {
		t.Fatalf("ToMap() should not include 'expandable' key")
	}
	if m["name"] != "x" {
		t.Fatalf("name = %v, want x", m["name"])
	}
	if m["description"] != "desc" {
		t.Fatalf("description = %v, want desc", m["description"])
	}
}

func _add_memory(parameters map[string]any) any {
	return "ok"
}

func TestAutoGeneratedToolDefaultNameAndDescriptionMatchPythonPattern(t *testing.T) {
	parent := NewBaseTool("memory", "desc", true)
	tool := NewAutoGeneratedTool(&parent, _add_memory, "", "")

	if got := tool.GetName(); got != "memory_add_memory" {
		t.Fatalf("name = %q, want %q", got, "memory_add_memory")
	}
	if got := tool.GetDescription(); got != "执行 _add_memory" {
		t.Fatalf("description = %q, want %q", got, "执行 _add_memory")
	}
}
