// 可展开工具模板 - 多功能工具
//
// 对应 Python 版本: examples/custom_tools/expandable_tool_template.py
// 展示如何创建可展开为多个子工具的多功能工具（CRUD 资源管理器）。
package main

import (
	"fmt"
	"strings"

	"helloagents-go/hello_agents/tools"
)

// ExpandableToolTemplate 可展开工具模板
type ExpandableToolTemplate struct {
	tools.BaseTool
	storagePath string
	dataStore   map[string]map[string]any
}

func NewExpandableToolTemplate(storagePath string) *ExpandableToolTemplate {
	t := &ExpandableToolTemplate{
		storagePath: storagePath,
		dataStore:   make(map[string]map[string]any),
	}
	t.Name = "expandable"
	t.Description = "可展开的多功能工具模板"
	t.Expandable = true
	return t
}

func (t *ExpandableToolTemplate) GetName() string        { return t.Name }
func (t *ExpandableToolTemplate) GetDescription() string { return t.Description }
func (t *ExpandableToolTemplate) GetParameters() []tools.ToolParameter {
	return []tools.ToolParameter{}
}
func (t *ExpandableToolTemplate) RunWithTiming(p map[string]any) tools.ToolResponse {
	return t.BaseTool.RunWithTiming(p)
}
func (t *ExpandableToolTemplate) ARun(p map[string]any) tools.ToolResponse { return t.Run(p) }
func (t *ExpandableToolTemplate) ARunWithTiming(p map[string]any) tools.ToolResponse {
	return t.Run(p)
}

func (t *ExpandableToolTemplate) Run(parameters map[string]any) tools.ToolResponse {
	return tools.Error(
		"此工具需要展开使用，请使用子工具: expandable_create, expandable_read, expandable_update, expandable_delete, expandable_list",
		tools.ToolErrorCodeInternalError,
		nil,
	)
}

func (t *ExpandableToolTemplate) GetExpandedTools() []tools.Tool {
	createTool := tools.NewAutoGeneratedTool(t, t.createAction, "expandable_create", "创建新资源")
	createTool.Parameters = map[string]tools.ToolParameter{
		"name":    {Name: "name", Type: "string", Description: "资源名称", Required: true},
		"content": {Name: "content", Type: "string", Description: "资源内容", Required: true},
		"tags":    {Name: "tags", Type: "string", Description: "标签（逗号分隔）", Required: false},
	}

	readTool := tools.NewAutoGeneratedTool(t, t.readAction, "expandable_read", "读取资源")
	readTool.Parameters = map[string]tools.ToolParameter{
		"name": {Name: "name", Type: "string", Description: "资源名称", Required: true},
	}

	updateTool := tools.NewAutoGeneratedTool(t, t.updateAction, "expandable_update", "更新资源")
	updateTool.Parameters = map[string]tools.ToolParameter{
		"name":    {Name: "name", Type: "string", Description: "资源名称", Required: true},
		"content": {Name: "content", Type: "string", Description: "新内容（可选）", Required: false},
		"tags":    {Name: "tags", Type: "string", Description: "新标签（可选，逗号分隔）", Required: false},
	}

	deleteTool := tools.NewAutoGeneratedTool(t, t.deleteAction, "expandable_delete", "删除资源")
	deleteTool.Parameters = map[string]tools.ToolParameter{
		"name":    {Name: "name", Type: "string", Description: "资源名称", Required: true},
		"confirm": {Name: "confirm", Type: "boolean", Description: "确认删除（必须为 true）", Required: true},
	}

	listTool := tools.NewAutoGeneratedTool(t, t.listAction, "expandable_list", "列出所有资源")
	listTool.Parameters = map[string]tools.ToolParameter{
		"filter_tag": {Name: "filter_tag", Type: "string", Description: "按标签过滤（可选）", Required: false},
	}

	return []tools.Tool{createTool, readTool, updateTool, deleteTool, listTool}
}

func (t *ExpandableToolTemplate) createAction(params map[string]any) tools.ToolResponse {
	name, _ := params["name"].(string)
	content, _ := params["content"].(string)
	tagsStr, _ := params["tags"].(string)

	if _, exists := t.dataStore[name]; exists {
		return tools.Error(
			fmt.Sprintf("资源 '%s' 已存在", name),
			tools.ToolErrorCodeConflict,
			map[string]any{"name": name},
		)
	}

	tags := parseTags(tagsStr)
	resource := map[string]any{
		"name":       name,
		"content":    content,
		"tags":       tags,
		"created_at": "2025-02-21T00:00:00Z",
	}
	t.dataStore[name] = resource

	return tools.Success(
		fmt.Sprintf("资源 '%s' 创建成功", name),
		map[string]any{"resource": resource},
	)
}

func (t *ExpandableToolTemplate) readAction(params map[string]any) tools.ToolResponse {
	name, _ := params["name"].(string)

	resource, exists := t.dataStore[name]
	if !exists {
		return tools.Error(
			fmt.Sprintf("资源 '%s' 不存在", name),
			tools.ToolErrorCodeNotFound,
			map[string]any{"name": name},
		)
	}

	tags, _ := resource["tags"].([]string)
	text := fmt.Sprintf("资源 '%s':\n内容: %s\n标签: %s",
		name, resource["content"], strings.Join(tags, ", "))

	return tools.Success(text, resource)
}

func (t *ExpandableToolTemplate) updateAction(params map[string]any) tools.ToolResponse {
	name, _ := params["name"].(string)

	resource, exists := t.dataStore[name]
	if !exists {
		return tools.Error(
			fmt.Sprintf("资源 '%s' 不存在", name),
			tools.ToolErrorCodeNotFound,
			map[string]any{"name": name},
		)
	}

	var updatedFields []string

	if content, ok := params["content"].(string); ok && content != "" {
		resource["content"] = content
		updatedFields = append(updatedFields, "content")
	}

	if tagsStr, ok := params["tags"].(string); ok && tagsStr != "" {
		resource["tags"] = parseTags(tagsStr)
		updatedFields = append(updatedFields, "tags")
	}

	if len(updatedFields) == 0 {
		return tools.Error("至少需要提供 content 或 tags 参数", tools.ToolErrorCodeInvalidParam, nil)
	}

	resource["updated_at"] = "2025-02-21T00:00:00Z"

	return tools.Success(
		fmt.Sprintf("资源 '%s' 更新成功，更新字段: %s", name, strings.Join(updatedFields, ", ")),
		map[string]any{"resource": resource, "updated_fields": updatedFields},
	)
}

func (t *ExpandableToolTemplate) deleteAction(params map[string]any) tools.ToolResponse {
	name, _ := params["name"].(string)
	confirm, _ := params["confirm"].(bool)

	if !confirm {
		return tools.Error("删除操作需要确认，请设置 confirm=true", tools.ToolErrorCodeInvalidParam, nil)
	}

	resource, exists := t.dataStore[name]
	if !exists {
		return tools.Error(
			fmt.Sprintf("资源 '%s' 不存在", name),
			tools.ToolErrorCodeNotFound,
			map[string]any{"name": name},
		)
	}

	delete(t.dataStore, name)
	return tools.Success(
		fmt.Sprintf("资源 '%s' 已删除", name),
		map[string]any{"deleted_resource": resource},
	)
}

func (t *ExpandableToolTemplate) listAction(params map[string]any) tools.ToolResponse {
	filterTag, _ := params["filter_tag"].(string)

	var resources []map[string]any
	for _, r := range t.dataStore {
		if filterTag != "" {
			tags, _ := r["tags"].([]string)
			found := false
			for _, tag := range tags {
				if tag == filterTag {
					found = true
					break
				}
			}
			if !found {
				continue
			}
		}
		resources = append(resources, r)
	}

	return tools.Success(
		fmt.Sprintf("找到 %d 个资源", len(resources)),
		map[string]any{
			"resources":  resources,
			"count":      len(resources),
			"filter_tag": filterTag,
		},
	)
}

func parseTags(tagsStr string) []string {
	if tagsStr == "" {
		return []string{}
	}
	parts := strings.Split(tagsStr, ",")
	tags := make([]string, 0, len(parts))
	for _, p := range parts {
		trimmed := strings.TrimSpace(p)
		if trimmed != "" {
			tags = append(tags, trimmed)
		}
	}
	return tags
}

func main() {
	// 1. 创建可展开工具
	fmt.Println("=== 创建可展开工具 ===")
	tool := NewExpandableToolTemplate("./data")

	// 2. 查看展开后的子工具
	fmt.Println("\n=== 展开后的子工具 ===")
	expandedTools := tool.GetExpandedTools()
	for _, sub := range expandedTools {
		fmt.Printf("- %s: %s\n", sub.GetName(), sub.GetDescription())
	}
	fmt.Println()

	// 3. 注册到 ToolRegistry（自动展开）
	fmt.Println("=== 注册到 ToolRegistry ===")
	registry := tools.NewToolRegistry(nil)
	registry.RegisterTool(tool)

	fmt.Println("已注册的工具:")
	for _, name := range registry.ListTools() {
		fmt.Printf("- %s\n", name)
	}
	fmt.Println()

	// 4. 测试子工具（直接调用 Run 方法）
	fmt.Println("=== 测试子工具 ===")

	// 创建资源
	resp := expandedTools[0].Run(map[string]any{"name": "doc1", "content": "这是第一个文档", "tags": "重要, 文档"})
	fmt.Printf("创建: %s\n", resp.Text)

	// 读取资源
	resp = expandedTools[1].Run(map[string]any{"name": "doc1"})
	fmt.Printf("读取: %s\n", resp.Text)

	// 更新资源
	resp = expandedTools[2].Run(map[string]any{"name": "doc1", "content": "更新后的内容"})
	fmt.Printf("更新: %s\n", resp.Text)

	// 列出资源
	resp = expandedTools[4].Run(map[string]any{})
	fmt.Printf("列出: %s\n", resp.Text)

	// 删除资源
	resp = expandedTools[3].Run(map[string]any{"name": "doc1", "confirm": true})
	fmt.Printf("删除: %s\n", resp.Text)

	// 再次列出
	resp = expandedTools[4].Run(map[string]any{})
	fmt.Printf("删除后列出: %s\n", resp.Text)
}
