// 自定义工具完整示例
//
// 对应 Python 版本: examples/custom_tools/complete_example.py
// 展示如何使用 HelloAgents 框架创建和使用自定义工具的完整流程：
// 简单工具、函数式工具、可展开多功能工具、工具注册表的使用。
package main

import (
	"fmt"
	"strings"

	"helloagents-go/hello_agents/tools"
)

// =========================================
// 示例 1：最简单的自定义工具
// =========================================

// GreetingTool 问候工具
type GreetingTool struct {
	tools.BaseTool
}

func NewGreetingTool() *GreetingTool {
	t := &GreetingTool{}
	t.Name = "greeting"
	t.Description = "生成个性化的问候语"
	t.Parameters = map[string]tools.ToolParameter{
		"name": {Name: "name", Type: "string", Description: "要问候的人的名字", Required: true},
	}
	return t
}

func (t *GreetingTool) GetName() string                      { return t.Name }
func (t *GreetingTool) GetDescription() string               { return t.Description }
func (t *GreetingTool) GetParameters() []tools.ToolParameter { return t.BaseTool.GetParameters() }
func (t *GreetingTool) RunWithTiming(p map[string]any) tools.ToolResponse {
	return t.BaseTool.RunWithTiming(p)
}
func (t *GreetingTool) ARun(p map[string]any) tools.ToolResponse           { return t.Run(p) }
func (t *GreetingTool) ARunWithTiming(p map[string]any) tools.ToolResponse { return t.Run(p) }

func (t *GreetingTool) Run(parameters map[string]any) tools.ToolResponse {
	name, _ := parameters["name"].(string)
	if name == "" {
		return tools.Error("参数 'name' 不能为空", tools.ToolErrorCodeInvalidParam, nil)
	}
	greeting := fmt.Sprintf("你好，%s！欢迎使用 HelloAgents 框架！", name)
	return tools.Success(greeting, map[string]any{"name": name, "greeting": greeting})
}

// =========================================
// 示例 2：函数式工具
// =========================================

func wordCounter(input string) any {
	words := strings.Fields(input)
	return fmt.Sprintf("文本包含 %d 个单词", len(words))
}

// =========================================
// 示例 3：可展开的多功能工具
// =========================================

// TextProcessorTool 文本处理工具集
type TextProcessorTool struct {
	tools.BaseTool
}

func NewTextProcessorTool() *TextProcessorTool {
	t := &TextProcessorTool{}
	t.Name = "text_processor"
	t.Description = "文本处理工具集，包含多种文本处理功能"
	t.Expandable = true
	return t
}

func (t *TextProcessorTool) GetName() string        { return t.Name }
func (t *TextProcessorTool) GetDescription() string { return t.Description }
func (t *TextProcessorTool) GetParameters() []tools.ToolParameter {
	return []tools.ToolParameter{}
}
func (t *TextProcessorTool) RunWithTiming(p map[string]any) tools.ToolResponse {
	return t.BaseTool.RunWithTiming(p)
}
func (t *TextProcessorTool) ARun(p map[string]any) tools.ToolResponse           { return t.Run(p) }
func (t *TextProcessorTool) ARunWithTiming(p map[string]any) tools.ToolResponse { return t.Run(p) }

func (t *TextProcessorTool) Run(parameters map[string]any) tools.ToolResponse {
	return tools.Error(
		"请使用展开后的子工具: text_uppercase, text_lowercase, text_reverse",
		tools.ToolErrorCodeInternalError,
		nil,
	)
}

func (t *TextProcessorTool) GetExpandedTools() []tools.Tool {
	uppercaseTool := tools.NewAutoGeneratedTool(
		t,
		func(params map[string]any) tools.ToolResponse {
			text, _ := params["text"].(string)
			result := strings.ToUpper(text)
			return tools.Success(
				fmt.Sprintf("转换结果: %s", result),
				map[string]any{"original": text, "result": result},
			)
		},
		"text_uppercase",
		"转换为大写",
	)
	uppercaseTool.Parameters = map[string]tools.ToolParameter{
		"text": {Name: "text", Type: "string", Description: "要转换的文本", Required: true},
	}

	lowercaseTool := tools.NewAutoGeneratedTool(
		t,
		func(params map[string]any) tools.ToolResponse {
			text, _ := params["text"].(string)
			result := strings.ToLower(text)
			return tools.Success(
				fmt.Sprintf("转换结果: %s", result),
				map[string]any{"original": text, "result": result},
			)
		},
		"text_lowercase",
		"转换为小写",
	)
	lowercaseTool.Parameters = map[string]tools.ToolParameter{
		"text": {Name: "text", Type: "string", Description: "要转换的文本", Required: true},
	}

	reverseTool := tools.NewAutoGeneratedTool(
		t,
		func(params map[string]any) tools.ToolResponse {
			text, _ := params["text"].(string)
			runes := []rune(text)
			for i, j := 0, len(runes)-1; i < j; i, j = i+1, j-1 {
				runes[i], runes[j] = runes[j], runes[i]
			}
			result := string(runes)
			return tools.Success(
				fmt.Sprintf("反转结果: %s", result),
				map[string]any{"original": text, "result": result},
			)
		},
		"text_reverse",
		"反转文本",
	)
	reverseTool.Parameters = map[string]tools.ToolParameter{
		"text": {Name: "text", Type: "string", Description: "要反转的文本", Required: true},
	}

	return []tools.Tool{uppercaseTool, lowercaseTool, reverseTool}
}

func main() {
	fmt.Println("============================================================")
	fmt.Println("HelloAgents 自定义工具完整示例")
	fmt.Println("============================================================")
	fmt.Println()

	// 1. 创建工具注册表
	fmt.Println("📦 步骤 1: 创建工具注册表")
	registry := tools.NewToolRegistry(nil)
	fmt.Println("✅ 工具注册表创建成功")
	fmt.Println()

	// 2. 注册简单工具
	fmt.Println("📦 步骤 2: 注册简单工具")
	greetingTool := NewGreetingTool()
	registry.RegisterTool(greetingTool, false)
	fmt.Println()

	// 3. 注册函数式工具
	fmt.Println("📦 步骤 3: 注册函数式工具")
	registry.RegisterFunction(wordCounter)
	fmt.Println()

	// 4. 注册可展开工具
	fmt.Println("📦 步骤 4: 注册可展开工具（自动展开为子工具）")
	textProcessor := NewTextProcessorTool()
	registry.RegisterTool(textProcessor)
	fmt.Println()

	// 5. 查看所有已注册的工具
	fmt.Println("📋 步骤 5: 查看所有已注册的工具")
	toolNames := registry.ListTools()
	fmt.Printf("已注册 %d 个工具:\n", len(toolNames))
	for _, name := range toolNames {
		fmt.Printf("  - %s\n", name)
	}
	fmt.Println()

	// 6. 直接测试工具
	fmt.Println("============================================================")
	fmt.Println("🧪 直接测试工具")
	fmt.Println("============================================================")
	fmt.Println()

	// 测试问候工具
	fmt.Println("测试 1: 问候工具")
	resp := greetingTool.Run(map[string]any{"name": "张三"})
	fmt.Printf("  状态: %s\n", resp.Status)
	fmt.Printf("  结果: %s\n", resp.Text)
	fmt.Println()

	// 测试函数工具（通过 Registry 执行，函数式工具走不同路径）
	fmt.Println("测试 2: 单词计数工具（函数式）")
	resp = registry.ExecuteTool("wordCounter", "Hello World from HelloAgents")
	fmt.Printf("  状态: %s\n", resp.Status)
	fmt.Printf("  结果: %s\n", resp.Text)
	fmt.Println()

	// 测试可展开工具的子工具（直接调用 Run）
	expandedTools := textProcessor.GetExpandedTools()
	fmt.Println("测试 3: 文本处理工具（大写）")
	resp = expandedTools[0].Run(map[string]any{"text": "hello world"})
	fmt.Printf("  状态: %s\n", resp.Status)
	fmt.Printf("  结果: %s\n", resp.Text)
	fmt.Println()

	fmt.Println("测试 4: 文本处理工具（反转）")
	resp = expandedTools[2].Run(map[string]any{"text": "HelloAgents"})
	fmt.Printf("  状态: %s\n", resp.Status)
	fmt.Printf("  结果: %s\n", resp.Text)
	fmt.Println()

	// 7. Agent 使用提示
	fmt.Println("============================================================")
	fmt.Println("🤖 在 Agent 中使用工具")
	fmt.Println("============================================================")
	fmt.Println()
	fmt.Println("提示: 要在 Agent 中使用工具，需要配置 LLM。")
	fmt.Println("示例代码:")
	fmt.Println(`  llm, _ := core.NewHelloAgentsLLM(...)`)
	fmt.Println(`  agent, _ := agents.NewReActAgent("assistant", llm, "", &cfg, registry, 10)`)
	fmt.Println(`  result, _ := agent.Arun("请用 greeting 工具问候李四", hooks, nil)`)
	fmt.Println()

	fmt.Println("============================================================")
	fmt.Println("✅ 示例完成！")
	fmt.Println("============================================================")
}
